import {useState,useEffect,useRef,useMemo} from 'react';
import {EXP,KB,INS,SOURCES as S} from './data.js';
const PAGES=['Home','Explore Data','Compare','Flame AI','Fire Safety','Simulator','NASA Sources'];
const Src=({ids})=>ids.map(i=><a key={i} className="src" href={S[i].u} target="_blank" rel="noreferrer">{S[i].o} ↗</a>);
function Stars(){const r=useRef();useEffect(()=>{const c=r.current,x=c.getContext('2d');let w,h,id,p=[];const rm=matchMedia('(prefers-reduced-motion: reduce)').matches;
const rs=()=>{w=c.width=innerWidth;h=c.height=innerHeight;p=Array.from({length:Math.min(140,w/9)},()=>({x:Math.random()*w,y:Math.random()*h,z:Math.random()*1.5+.3,o:Math.random()}))};rs();addEventListener('resize',rs);
const f=()=>{x.clearRect(0,0,w,h);p.forEach(s=>{if(!rm){s.y-=s.z*.15;s.x+=Math.sin(s.o+s.y/90)*.15;if(s.y<0)s.y=h}x.fillStyle=`rgba(${s.z>1.3?'255,170,90':'200,220,255'},${.3+s.z/3})`;x.beginPath();x.arc(s.x,s.y,s.z,0,7);x.fill()});if(!rm)id=requestAnimationFrame(f)};f();return()=>{cancelAnimationFrame(id);removeEventListener('resize',rs)}},[]);return <canvas ref={r} className="stars"/>}
const Flame=({g=0,o=.21,flow=.3,size=1})=>{ // g:1=earth,0=micro
const tall=g?1.5:1,w=g?.8:1.1,blue=g?0:1-Math.min(1,flow*1.5);const bright=.4+o*2;
return <svg className="flame" viewBox="0 0 200 260" style={{transform:`scale(${size})`,'--b':blue,'--s':g?'.9s':'2.8s'}}><defs><filter id="bl"><feGaussianBlur stdDeviation="6"/></filter>
<radialGradient id="gA" cx="50%" cy="60%"><stop offset="0" stopColor={blue>.5?'#cfe8ff':'#fff3c4'}/><stop offset=".5" stopColor={blue>.5?'#4aa3ff':'#ffa31a'}/><stop offset="1" stopColor={blue>.5?'#1d4ed8':'#e8340c'} stopOpacity=".1"/></radialGradient></defs>
<ellipse className="fl" cx="100" cy={g?150:130} rx={42*w*bright} ry={g?60*tall*bright:50*bright} fill="url(#gA)" filter="url(#bl)" opacity=".85"/>
<ellipse className="fl" cx="100" cy={g?160:132} rx={24*w*bright} ry={g?42*tall*bright:30*bright} fill="url(#gA)"/><rect x="92" y="205" width="16" height="36" rx="4" fill="#394867"/></svg>};
function Home({go}){return <section className="hero"><div className="hero-t"><p className="eyebrow">NASA SPACE APPS 2026 · PROTOTYPE</p><h1>FLAME IN <span>FREEFALL</span></h1><p className="tag">Discover how fire behaves when gravity disappears.</p>
<p className="lead">On Earth, hot gas rises and flames are teardrop-shaped. On the ISS, NASA experiments such as BASS, ACME and FLEX studied flames without buoyancy to improve spacecraft fire safety. This project turns a small verified set of that research into an explorable dashboard.</p>
<div className="btns"><button className="btn pri" onClick={()=>go(1)}>EXPLORE NASA DATA</button><button className="btn" onClick={()=>go(3)}>ASK FLAME AI</button></div>
<div className="stats">{[['NASA EXPERIMENTS','1,500+','flames ignited in ACME',''],['MICROGRAVITY','<1 cm/s','airflow: dim blue, stable flames (BASS-II)',''],['FIRE SAFETY','100+','BASS/BASS-II tests guiding screening','']].map(a=><div className="card glass" key={a[0]}><small>{a[0]}</small><b>{a[1]}</b><span>{a[2]}</span></div>)}</div></div>
<div className="hero-f"><Flame g={0} flow={.1} size={1.25}/><i className="p p1"/><i className="p p2"/><i className="p p3"/><i className="p p4"/></div></section>}
function Explore(){const [q,setQ]=useState(''),[f,setF]=useState({});const opt=k=>[...new Set(EXP.flatMap(e=>k==='tags'?e.tags:[e[k]]))];
const F=[['Experiment','experiment'],['Fuel','fuelType'],['Gravity','gravity'],['Oxygen','o2'],['Airflow','flow'],['Flame behavior','tags']];
const rows=EXP.filter(e=>JSON.stringify(e).toLowerCase().includes(q.toLowerCase())&&F.every(([,k])=>!f[k]||(k==='tags'?e.tags.includes(f[k]):e[k]===f[k])));
return <><h2>Explore Experiments</h2><div className="filters glass"><input placeholder="Search experiments, fuels, behavior…" value={q} onChange={e=>setQ(e.target.value)}/>{F.map(([l,k])=><select key={k} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}><option value="">{l}: all</option>{opt(k).map(o=><option key={o}>{o}</option>)}</select>)}</div>
<div className="grid">{rows.map(e=><article className="card glass" key={e.id}><h3>{e.experiment}<small>{e.full}</small></h3>
{[['Fuel/material',e.fuel],['Gravity',e.gravity],['Oxygen',e.oxygen],['Airflow',e.airflow],['Flame behavior',e.flameBehavior],['Extinction',e.extinctionBehavior],['Safety relevance',e.safetyRelevance]].map(([a,b])=><p key={a}><em>{a}</em>{b}</p>)}<div><Src ids={e.src}/></div></article>)}{!rows.length&&<p>No matching experiments.</p>}</div></>}
function Compare(){const [sel,setSel]=useState(['bass','bass2']);const tog=id=>setSel(s=>s.includes(id)?(s.length>2?s.filter(x=>x!==id):s):s.length<3?[...s,id]:s);const E=EXP.filter(e=>sel.includes(e.id));
return <><h2>Compare Experiments</h2><p className="note">Select 2–3 experiments.</p><div className="chips">{EXP.map(e=><button key={e.id} className={'chip'+(sel.includes(e.id)?' on':'')} onClick={()=>tog(e.id)}>{e.experiment}</button>)}</div>
<div className="grid">{E.map(e=><article className="card glass" key={e.id}><h3>{e.experiment}</h3>{[['Objective',e.objective],['Fuel',e.fuel],['Oxygen',e.oxygen],['Airflow',e.airflow],['Geometry',e.geometry],['Flame behavior',e.flameBehavior],['Extinction',e.extinctionBehavior],['Fire-safety relevance',e.safetyRelevance]].map(([a,b])=><p key={a}><em>{a}</em>{b}</p>)}<Src ids={e.src}/></article>)}</div>
<div className="card glass"><h3>Maximum airflow tested (cm/s)</h3>{E.map(e=><div className="bar" key={e.id}><span>{e.experiment}</span>{e.maxFlow?<div><i style={{width:e.maxFlow/53*100+'%'}}/><b>{e.maxFlow}</b></div>:<div className="na">Data unavailable</div>}</div>)}<small>Values from NASA NTRS; chart drawn by this project.</small></div></>}
function AI(){const [q,setQ]=useState(''),[a,setA]=useState(null),[busy,setBusy]=useState(false);
const ask=t=>{t=(t||q).trim();if(!t)return;setQ(t);setBusy(true);setA(null);setTimeout(()=>{const l=t.toLowerCase();const hit=KB.map(k=>[k.k.filter(w=>l.includes(w)).length,k]).sort((x,y)=>y[0]-x[0])[0];setA(hit[0]?hit[1]:{key:'No verified answer in the local dataset for this question.',ev:'Data unavailable',rel:'—',src:['chal'],lim:'Try asking about microgravity, extinction, oxygen, airflow, BASS vs BASS-II, spacecraft safety or Mars.'});setBusy(false)},700)};
const ex=['How does fire behave in microgravity?','Compare BASS and BASS-II.','What affects flame extinction?','Which experiment is relevant to spacecraft fire safety?','What can this teach us about future Mars habitats?'];
return <><h2>Flame AI <span className="badge">AI-assisted project interpretation</span></h2><p className="note">Local rule-based assistant over the project’s verified dataset. Not an official NASA AI system.</p>
<div className="filters glass"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ask about microgravity fire…"/><button className="btn pri" onClick={()=>ask()}>ASK</button></div>
<div className="chips">{ex.map(x=><button key={x} className="chip" onClick={()=>ask(x)}>{x}</button>)}</div>
{busy&&<div className="pulse">Analyzing local dataset…</div>}
{a&&<div className="card glass ans">{[['KEY FINDING',a.key],['EVIDENCE',a.ev],['RELATED EXPERIMENT',EXP.find(e=>e.id===a.rel)?.experiment||'—']].map(([h,t])=><p key={h}><em>{h}</em>{t}</p>)}<p><em>NASA SOURCE</em><Src ids={a.src}/></p><p><em>LIMITATION</em>{a.lim}</p></div>}</>}
function Safety(){return <><h2>Fire Safety Insights</h2><p className="note">Cautious summaries tied to NASA evidence. “Data unavailable” marks gaps.</p><div className="grid g4">{INS.map(([t,x,s])=><article className="card glass" key={t}><h3>{t}</h3><p>{x}</p><Src ids={[s]}/></article>)}</div></>}
function Sim(){const [m,setM]=useState('MICROGRAVITY'),[o,setO]=useState(21),[fl,setFl]=useState(5);const earth=m==='EARTH';
return <><h2>Conceptual Flame Simulator</h2><p className="badge warn">Educational visualization only — NOT a real combustion physics simulation.</p>
<div className="sim"><div className="card glass ctrl"><div className="chips">{['EARTH','MICROGRAVITY'].map(x=><button key={x} className={'chip'+(m===x?' on':'')} onClick={()=>setM(x)}>{x}</button>)}</div>
<label>Oxygen: {o}%<input type="range" min="15" max="35" value={o} onChange={e=>setO(+e.target.value)}/></label><label>Airflow: {fl} cm/s<input type="range" min="0" max="50" value={fl} onChange={e=>setFl(+e.target.value)}/></label>
<label>Gravity: {earth?'1 g':'~0 g'}<input type="range" disabled value={earth?100:0}/></label>
<p className="note">{earth?'Buoyancy lifts hot gas: teardrop shape, flicker.':fl<1?'Very low flow: dim blue, rounded, stable.':'Flow stretches the flame; higher flow can make it flare.'}</p></div>
<div className="card glass stage"><Flame g={earth?1:0} o={o/100} flow={fl/10} size={.9+fl/120}/></div></div></>}
function Sources(){return <><h2>NASA Sources</h2><div className="grid">{Object.values(S).map(s=><a key={s.u} className="card glass" href={s.u} target="_blank" rel="noreferrer"><small>{s.o}</small><h3>{s.t}</h3></a>)}</div></>}
export default function App(){const [p,setP]=useState(0);const v=[<Home go={setP}/>,<Explore/>,<Compare/>,<AI/>,<Safety/>,<Sim/>,<Sources/>][p];
return <><Stars/><header><b onClick={()=>setP(0)}>🔥 FLAME IN FREEFALL</b><nav>{PAGES.map((n,i)=><button key={n} className={i===p?'on':''} onClick={()=>setP(i)}>{n}</button>)}</nav></header><main key={p} className="page">{v}</main><footer>Unofficial project prototype. Data from NASA sources listed; “Data unavailable” = not verified. Calculations and visualizations are project-derived.</footer></>}
