const U='Data unavailable';
export const SOURCES={
bass2:{t:'NASA Glenn – BASS-II (MSG)',o:'NASA Glenn',u:'https://www1.grc.nasa.gov/space/iss-research/msg/bass-2/'},
ntrs16:{t:'Combustion of Solids in Microgravity: Results from the BASS-II Experiment',o:'NASA NTRS 20160000593',u:'https://ntrs.nasa.gov/citations/20160000593'},
ntrs14:{t:'Thickness and Fuel Preheating Effects on Material Flammability in Microgravity from the BASS Experiment',o:'NASA NTRS 20140011099',u:'https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20140011099.pdf'},
fire23:{t:'Science in Space: Fire Safety in Space (Sept. 29, 2023)',o:'NASA Science / ISS Research',u:'https://www.nasa.gov/missions/station/iss-research/science-in-space-week-of-sept-29-2023-fire-safety-in-space/'},
acme:{t:'ACME Project: The Space Station’s Quest for the Secrets of Fire',o:'NASA',u:'https://www.nasa.gov/humans-in-space/space-stations-quest-for-the-secrets-of-fire/'},
acmeg:{t:'ACME paper (CSSCI 2022 Spring Technical Meeting)',o:'NASA Glenn',u:'https://www1.grc.nasa.gov/wp-content/uploads/ACME-CSSCI-paper-20220402.pdf'},
cir:{t:'Studying Combustion and Fire Safety',o:'NASA Space Station research',u:'https://www.nasa.gov/missions/station/iss-research/studying-combustion-and-fire-safety/'},
st14:{t:'ISS Daily Summary Report – 04/10/14',o:'NASA ISS On-Orbit Status Report',u:'https://www.nasa.gov/blogs/stationreport/2014/04/10/iss-daily-summary-report-04-10-14/'},
chal:{t:'Flame in Freefall – Space Apps 2026 challenge',o:'NASA Space Apps',u:'https://www.spaceappschallenge.org/2026/challenges/flame-in-freefall-ai-powered-fire-safety-insights-from-microgravity-combustion-data/'}};
export const EXP=[
{id:'bass',experiment:'BASS',full:'Burning and Suppression of Solids',objective:'Examine how a variety of solid fuels burn and can be extinguished in microgravity.',fuel:'Thin and thick flat samples, acrylic spheres, candles',fuelType:'Solid',gravity:'Microgravity (ISS)',oxygen:'Nitrogen dilution studied; specific O₂ values: '+U,o2:'Varied',airflow:'Up to 40 cm/s in a small wind tunnel',flow:'Controlled flow',maxFlow:40,geometry:'Small wind tunnel (opposed & concurrent flow)',flameBehavior:'Very sensitive to flow speed at 0–5 cm/s; below 1 cm/s flames became dim blue and very stable.',tags:['Dim blue / stable'],extinctionBehavior:'A nitrogen jet was used in some tests to try to extinguish flames; the smallest acrylic-slab flames burned over 5 min before self-extinguishing.',safetyRelevance:'Informs flammability screening, detection and suppression for spacecraft. 59 burn tests analyzed.',src:['ntrs14','fire23']},
{id:'bass2',experiment:'BASS-II',full:'Burning and Suppression of Solids – II',objective:'Test whether materials with adequate ventilation burn as well or better in microgravity than in normal gravity at identical conditions.',fuel:'Thin and thick flat samples, fabrics, acrylic slabs, spheres, cylinders',fuelType:'Solid',gravity:'Microgravity (ISS)',oxygen:'Varied; reduced-O₂ fabric tests (one sample self-extinguished at lower O₂)',o2:'Varied',airflow:'Up to 53 cm/s',flow:'Controlled flow',maxFlow:53,geometry:'Small wind tunnel in the Microgravity Science Glovebox (opposed & concurrent flow)',flameBehavior:'Sensitive to flow in 0–5 cm/s; dim blue and stable below 1 cm/s but can flare up quickly if airflow suddenly increases.',tags:['Dim blue / stable','Flare-up risk'],extinctionBehavior:'Lower oxygen and flow changes affected extinction; one fabric sample self-extinguished at reduced O₂ (2014 ISS report).',safetyRelevance:'Guides spacecraft materials flammability screening; well over 100 tests including BASS-I.',src:['ntrs16','bass2','st14']},
{id:'acme',experiment:'ACME',full:'Advanced Combustion via Microgravity Experiments',objective:'Six independent studies of non-premixed gaseous-fuel flames to improve efficiency and reduce pollutants; also relevant to flammability research.',fuel:'Gaseous fuels (e.g., ethylene, n-butane in CFI-G tests)',fuelType:'Gas',gravity:'Microgravity (ISS)',oxygen:'Elevated-O₂ ethylene flames reported burning for minutes; full range: '+U,o2:'Elevated',airflow:U,flow:'Data unavailable',maxFlow:null,geometry:'Combustion Integrated Rack insert; spherical and co-flow burners',flameBehavior:'First quasi-steady non-premixed spherical flames; non-premixed cool flames without ground-test enhancements.',tags:['Spherical','Cool flame'],extinctionBehavior:'Larger spherical flames showed extinction driven by radiative heat loss (Flame Design).',safetyRelevance:'Fundamental flame physics; over 1,500 flames ignited (Oct 2017–Feb 2022). Direct spacecraft-fire guidance: '+U,src:['acme','acmeg']},
{id:'flex',experiment:'FLEX / FLEX-2',full:'FLame Extinguishment Experiments',objective:'FLEX: effectiveness of fire suppressants. FLEX-2: droplet burn rates, soot formation conditions, fuel-mixture evaporation.',fuel:'Liquid droplets (heptane, methanol; iso-octane/heptane mixtures in FLEX-2)',fuelType:'Liquid',gravity:'Microgravity (ISS)',oxygen:U,o2:'Data unavailable',airflow:U,flow:'Data unavailable',maxFlow:null,geometry:'Single droplets in the Multi-user Droplet Combustion Apparatus (CIR)',flameBehavior:'Discovery of cool flames: fuel kept “burning” after the visible flame was extinguished; cool flames yield carbon monoxide and formaldehyde.',tags:['Cool flame'],extinctionBehavior:'Heptane droplets sometimes continued to burn after the visible flame went out.',safetyRelevance:'Informs suppressant effectiveness and suggests extinguished-looking fires may not be fully out. Quantitative thresholds: '+U,src:['cir']}];
export const KB=[
{k:['microgravity','behave','gravity','fire behave'],key:'Without buoyancy, flames change shape and can burn very differently: low-flow flames can become dim blue and stable, and spherical flames become possible.',ev:'BASS: flames became dim blue and very stable below 1 cm/s. ACME: first quasi-steady spherical non-premixed flames.',rel:'bass2',src:['ntrs16','acme'],lim:'ISS data cover specific fuels, flows and chambers; they do not describe every fire.'},
{k:['bass-ii','bass ii','bass2','compare bass','bass and'],key:'BASS-II extended BASS: more fuel geometries, higher tested airflow (53 vs 40 cm/s) and explicit oxygen-concentration effects.',ev:'BASS: flat samples, spheres, candles, up to 40 cm/s. BASS-II: adds slabs, cylinders, fabrics, up to 53 cm/s; well over 100 tests including BASS-I.',rel:'bass2',src:['ntrs14','ntrs16'],lim:'Exact oxygen values per test are not in this dataset.'},
{k:['extinct','extinguish','suppress','put out'],key:'Extinction depends on oxygen, airflow, fuel and heat loss. Cool flames can persist after the visible flame disappears.',ev:'BASS-II: one fabric self-extinguished at lower O₂. ACME: radiative heat loss caused extinction of larger spherical flames. FLEX: heptane droplets kept burning after visible extinction.',rel:'flex',src:['st14','acme','cir'],lim:'Numerical extinction limits: Data unavailable here.'},
{k:['spacecraft','safety','relevant','screening','material'],key:'BASS/BASS-II are the most directly tied to spacecraft materials flammability screening and to detection/suppression design.',ev:'NASA states BASS-II guides materials flammability screening for spacecraft; the current screening is based on an upward-burning test, the worst case on Earth.',rel:'bass2',src:['bass2','fire23'],lim:'Screening-standard details are not reproduced in this dataset.'},
{k:['mars','moon','habitat','lunar','future'],key:'Microgravity results show which factors (O₂, flow, fuel) to control, but Moon/Mars partial gravity is not covered by the ISS experiments here.',ev:'The experiments in this dataset were conducted on the ISS in microgravity.',rel:'bass',src:['fire23'],lim:'Moon/Mars-specific values: Data unavailable. Any habitat conclusion is an extrapolation.'},
{k:['oxygen','o2'],key:'Lower oxygen can lead to self-extinguishing; elevated oxygen lets some flames burn for minutes.',ev:'BASS-II reduced-O₂ fabric test; ACME ethylene flames at elevated O₂.',rel:'bass2',src:['st14','acmeg'],lim:'Quantitative O₂ thresholds: Data unavailable.'},
{k:['air','flow','ventilation'],key:'Microgravity flames are very sensitive to airflow below ~5 cm/s, and a stable low-flow flame can flare up if flow suddenly rises.',ev:'BASS and BASS-II tunnel tests at 0–5 cm/s.',rel:'bass2',src:['ntrs16','ntrs14'],lim:'Applies to the tested wind-tunnel geometry.'}];
export const INS=[
['FLAME GROWTH','Thin fabrics reach a steady spread rate and limiting length; lower pressure slows spread.','fire23'],
['FLAME STABILITY','Flames below 1 cm/s are dim blue and stable, yet can flare up with a sudden airflow increase.','ntrs16'],
['EXTINCTION','Heat loss, oxygen and flow all matter; cool flames can outlive the visible flame.','acme'],
['OXYGEN EFFECT','A reduced-O₂ fabric sample self-extinguished in BASS-II; quantitative limits are Data unavailable.','st14'],
['AIRFLOW EFFECT','Flame response is highly sensitive from 0 to 5 cm/s and nearly immediate.','ntrs14'],
['FUEL EFFECT','Fuel thickness, preheating and geometry changed growth and spread in BASS tests.','ntrs14'],
['SPACECRAFT FIRE SAFETY','BASS-II results feed materials screening and detection/suppression models.','bass2'],
['MOON/MARS RELEVANCE','Not directly tested in these ISS studies: Data unavailable. Treat as an open research question.','fire23']];
